iab ccopy :set pastei/* Copyright 2009 ~/.vim/abbrs2vim.py * Licensed for distribution under the GPL version 2. * * ___Program purpose... */:set nopastegg/___:nohlsearch
iab cmain :set pastei// vim: sw=4 sts=4#include <stdio.h>#include <stdlib.h>int main(void) {    ___    return 0;}:set nopastegg/___:nohlsearch
iab cmaina :set pastei// vim: sw=4 sts=4#include <stdio.h>#include <stdlib.h>int main(int argc, char *argv[]) {    ___    return 0;}:set nopastegg/___:nohlsearch
iab cppmain :set pastei// vim: sw=4 sts=4#include <iostream>#include <string>#include <vector>int main(void) {    ___    return 0;}:set nopastegg/___:nohlsearch
iab cppmaina :set pastei// vim: sw=4 sts=4#include <iostream>#include <string>#include <vector>int main(int argc, char** argv) {  ___  return 0;}:set nopastegg/___:nohlsearch
iab jmain :set pasteipublic class ___ClassName {  public static void main(String[] args) {    // code  }}:set nopastegg/___:nohlsearch
iab latexreport :set pastei\documentclass[a4paper,12pt]{report}% These packages need to be included to insert pictures into your report\usepackage[pdftex]{graphicx}% Better maths suport\usepackage{amssymb,amsmath}% Support links in the pdf file\usepackage{hyperref}% Put a medium sized gap between paragraphs\setlength{\parskip}{\medskipamount}% Don't indent the start of new paragraphs\setlength{\parindent}{0pt}% Changes section numbering somehow...\renewcommand{\thesection}{\arabic{section}}\title{The Title goes here}\author{  ___First Author\\  (email: {\tt ___user@example.com}) \\}\begin{document}%The \maketitle command puts today's date on your document\maketitle\begin{abstract}___Abstract goes here\end{abstract}% The table of contents is made automatically\tableofcontents\newpage\listoffigures\newpage\section{___First Section}%The {99} in the commad below tells LaTeX not to expect any numbers wider%than the width of the number 99 (ie. there are no more than 99 referenced% items)\begin{thebibliography}{99}% The command below gives the item a label which is used in citing references\bibitem{abc}J. Author, {\em The title of the Article}, Name of the Journal. Volume  (2009), page(s).                                                    \end{thebibliography}\end{document}:set nopastegg/___:nohlsearch
iab pycopy :set pastei# Copyright 2009 ~/.vim/abbrs2vim.py# Licensed for distribution under the GPL version 2, check COPYING for details# ___Program purpose:set nopastegg/___:nohlsearch
iab pymain :set pasteidef main():	___ passif __name__ == "__main__":	main():set nopastegg/___:nohlsearch
iab xhtmltemplate :set pastei<?xml version='1.0' encoding='UTF-8'?><!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.1//EN"  "http://www.w3.org/TR/xhtml11/DTD/xhtml11.dtd"><html xmlns="http://www.w3.org/1999/xhtml" xml:lang="en"><head>	<title>___</title>	<link rel="stylesheet" type="text/css" href="___" />	<script type="text/javascript" src="___"/></head><body>___</body></html>:set nopastegg/___:nohlsearch
iab YDATE :set pastei<C-R>=strftime("%Y-%m-%d")<CR>:set nopastea
