#! zsh

# This file sets up the environment correctly. It gets run for every shell,
# so it must be fast. Also, starting a shell within a shell shouldn't change
# the environment. The path manipulation functions are useful for this.

# Files will be created by default rwx user only
umask 0022

# General environment settings
export IFS=$' \t\n'
export PAGER="less"
if [[ -n "$NVIM" ]]; then
	export EDITOR="nvim --server $NVIM --remote-wait"
else
	export EDITOR="nvim"
fi
export CVS_RSH="ssh"
export RSYNC_RSH="ssh"
export PYTHONSTARTUP="${HOME}/.pythonrc.py"
HISTSIZE="10000"
SAVEHIST="1000000"
HISTFILE=~/.zsh_history
HISTORY_IGNORE="history*:clear:*/*\.del*:ls:[bf]g:exit"
setopt APPEND_HISTORY
setopt HIST_IGNORE_DUPS
setopt HIST_IGNORE_SPACE
setopt HIST_EXPIRE_DUPS_FIRST
setopt HIST_REDUCE_BLANKS

# Load the zsh functions
source "${HOME}/.zsh/functions"

# The current directory shouldn't be in the path
pathremove .
