#! zsh

# Keybindings for zsh - translated from inputrc

# Use emacs keymap as base
bindkey -e

# Completion configuration
zstyle ':completion:*' matcher-list 'm:{a-zA-Z}={A-Za-z}'  # completion-ignore-case on
zstyle ':completion:*' menu select
zstyle ':completion:*' expand prefix suffix               # expand-tilde on
setopt NO_GLOB_DOTS                                       # match-hidden-files off
setopt NO_LIST_AMBIGUOUS                                  # show-all-if-unmodified on

export WORDCHARS='*?_-.[]~=&;!#$%^(){}<>/\|`'"'"'"@:'

bindkey '^W' backward-kill-word

# C-g: delete word with standard punctuation WORDCHARS
_backward-kill-word-punctuated() {
	local WORDCHARS=''
	zle .backward-kill-word
}
zle -N _backward-kill-word-punctuated
bindkey '^G' _backward-kill-word-punctuated

# M-g / M-f: move backward/forward word using same WORDCHARS as C-g
_backward-word-punctuated() {
	local WORDCHARS=''
	zle .backward-word
}
zle -N _backward-word-punctuated
bindkey '^[G' _backward-word-punctuated

_forward-word-punctuated() {
	local WORDCHARS=''
	zle .forward-word
}
zle -N _forward-word-punctuated
bindkey '^[F' _forward-word-punctuated

# Basic movement with M-b / M-gn
bindkey '^[b' backward-word
bindkey '^[n' forward-word

bindkey '^[[3~' delete-char

# History navigation
bindkey '^J' down-line-or-history
bindkey '^K' up-line-or-history

# Arrow keys for history search (matches prefix, cursor at end of line)
_history-search-backward-eol() {
	if [[ $LASTWIDGET != _history-search-*-eol ]]; then
		_HISTORY_SEARCH_CURSOR=$CURSOR
	fi
	CURSOR=$_HISTORY_SEARCH_CURSOR
	zle history-beginning-search-backward
	zle end-of-line
}
zle -N _history-search-backward-eol
_history-search-forward-eol() {
	if [[ $LASTWIDGET != _history-search-*-eol ]]; then
		_HISTORY_SEARCH_CURSOR=$CURSOR
	fi
	CURSOR=$_HISTORY_SEARCH_CURSOR
	zle history-beginning-search-forward
	zle end-of-line
}
zle -N _history-search-forward-eol
bindkey '\e[A' _history-search-backward-eol
bindkey '\e[B' _history-search-forward-eol

# Page up/down for history search
bindkey '\e[5~' history-search-backward
bindkey '\e[6~' history-search-forward

# Re-render prompt on Enter so %* shows the time the command was submitted
zle-line-accept() {
	zle reset-prompt
	zle .accept-line
}
zle -N accept-line zle-line-accept
