#! zsh

# Keybindings for zsh - translated from inputrc

# Use emacs keymap as base
bindkey -e

# Completion configuration
zstyle ':completion:*' matcher-list 'm:{a-zA-Z}={A-Za-z}'  # completion-ignore-case on
zstyle ':completion:*' menu select
zstyle ':completion:*' expand prefix suffix               # expand-tilde on
setopt NO_GLOB_DOTS                                       # match-hidden-files off
setopt NO_LIST_AMBIGUOUS                                  # show-all-if-unmodified on

export WORDCHARS='*?_-.[]~=&;!#$%^(){}<>/\|`'"'"'"@:'

bindkey '^W' backward-kill-word

# C-g: delete word with standard punctuation WORDCHARS
_backward-kill-word-punctuated() {
	local WORDCHARS=''
	zle .backward-kill-word
}
zle -N _backward-kill-word-punctuated
bindkey '^G' _backward-kill-word-punctuated

# M-g / M-f: move backward/forward word using same WORDCHARS as C-g
_backward-word-punctuated() {
	local WORDCHARS=''
	zle .backward-word
}
zle -N _backward-word-punctuated
bindkey '^[G' _backward-word-punctuated

_forward-word-punctuated() {
	local WORDCHARS=''
	zle .forward-word
}
zle -N _forward-word-punctuated
bindkey '^[F' _forward-word-punctuated

# Basic movement with M-b / M-gn
bindkey '^[b' backward-word
bindkey '^[n' forward-word

bindkey '^[[3~' delete-char

# History navigation
bindkey '^J' down-line-or-history
bindkey '^K' up-line-or-history

# Arrow keys for history search
bindkey '\e[A' history-search-backward
bindkey '\e[B' history-search-forward

# Page up/down for history search
bindkey '\e[5~' history-search-backward
bindkey '\e[6~' history-search-forward
