#! zsh

# common
alias rm='rm -i'
alias ll='ls -hlF'
alias la='ls -ha'
alias  l='ls -halF'
alias less='less -R'
alias tmux-create='~/dotfiles/tmux-create'
alias tm='tmux'
export PYTHONSTARTUP=$HOME/.pythonrc.py
export GOPATH=$HOME/gocode
alias tat='tmux attach -t'
export TERM=xterm-256color

if [ $(uname) = 'Darwin' ]; then
	alias top='top -s1 -F -R -o cpu'
	alias ls='ls -G'
	alias grep='grep --color=auto'
	alias volcheck='sudo fsck_hfs -f -c 2200m' # /dev/disk2
	alias postgres-start='pg_ctl -D /usr/local/var/postgres -l /usr/local/var/postgres/server.log start'
	alias postgres-stop='pg_ctl -D /usr/local/var/postgres stop -s -m fast'
	alias fixopenwith='/System/Library/Frameworks/CoreServices.framework/Frameworks/LaunchServices.framework/Support/lsregister -kill -r -domain local -domain system -domain user'
	alias proxy='export http_proxy=$(networksetup -getwebproxy Wi-Fi | awk '\''{ if(NR == 1) enabled=$2; else if(NR == 2) server=$2; else if(NR == 3) port=$2;} END {if(enabled == "Yes") print "http://" server ":" port}'\'')'

	export COPYFILE_DISABLE=true #for stopping those damned ._ files
	export PATH=/opt/homebrew/bin:/opt/homebrew/sbin:/usr/local/bin:/usr/local/sbin:/usr/bin:/bin:/usr/sbin:/sbin:/usr/X11/bin:$(xcode-select -print-path)/usr/bin:$HOME/Applications:/Library/TeX/texbin:/Users/dom/.deno/bin/:$HOME/.local/bin:$HOME/.claude/local:$HOME/.local/share/nvim/lazy/fzf/bin:/opt/homebrew/opt/libpq/bin:
	export TEXINPUTS=".:.//:/usr/local/texlive/2023basic/texmf-dist/tex/latex//:/usr/local/texlive/2023basic/texmf-dist/tex/generic//:$HOME/working/reposs/tex//:"
	export GNUTERM=x11 # for Octave

	ssource "${HOME}/.secrets"

	# zsh completion
	FPATH="$(brew --prefix)/share/zsh/site-functions:${FPATH}"
	autoload -Uz compinit && compinit
else
	alias ls='ls --color=auto'
	alias grep='grep --color=auto'

	# local path modifications
	export PATH=$HOME/bin:$HOME/local/bin:$GOPATH/bin:$PATH:$HOME/repos/depot_tools

	autoload -Uz compinit && compinit
fi
