#! bash

# This file sets up the environment correctly. It gets run for every shell,
# so it must be fast. Also, starting a shell within a shell shouldn't change
# the environment. The path manipulation functions are useful for this.

# Files will be created by default rwx user only
umask 0022

# General environment settings
export IFS=$' \t\n'
export PAGER="less"
export EDITOR="nvim"
export CVS_RSH="ssh"
export RSYNC_RSH="ssh"
export PYTHONSTARTUP="${HOME}/.pythonrc.py"
export INPUTRC=~/.inputrc
HISTSIZE="10000"
HISTFILESIZE="1000000"
HISTIGNORE="history*:clear:*/*\.del*:&:ls:[bf]g:exit"
HISTCONTROL="ignoreboth:erasedups"
shopt -s histappend
# PROMPT_COMMAND="history -n; history -w; history -c; history -r; $PROMPT_COMMAND"
shopt -s cmdhist

# Load the bash functions
source "${HOME}/.bash/functions"

# The current directory shouldn't be in the path
pathremove .
