#! bash

# common
alias rm='rm -i'
alias ll='ls -hlF'
alias la='ls -ha'
alias  l='ls -halF'
alias less='less -R'
alias tmux-create='~/dotfiles/tmux-create'
alias tm='tmux'
export PYTHONSTARTUP=$HOME/.pythonrc.py
export GOPATH=$HOME/gocode
alias tat='tmux attach -t'

if [ `uname` = 'Darwin' ]; then
	alias top='top -s1 -F -R -o cpu'
	# alias tmux='tmux -f ~/.tmux-osx.conf'
	alias vim='reattach-to-user-namespace vim'
	alias ls='ls -G'
	alias grep='grep --color=auto'
	alias volcheck='sudo fsck_hfs -f -c 2200m' # /dev/disk2
	alias postgres-start='pg_ctl -D /usr/local/var/postgres -l /usr/local/var/postgres/server.log start'
	alias postgres-stop='pg_ctl -D /usr/local/var/postgres stop -s -m fast'
	alias fixopenwith='/System/Library/Frameworks/CoreServices.framework/Frameworks/LaunchServices.framework/Support/lsregister -kill -r -domain local -domain system -domain user'
	alias proxy='export http_proxy=`networksetup -getwebproxy Wi-Fi | awk '\''{ if(NR == 1) enabled=$2; else if(NR == 2) server=$2; else if(NR == 3) port=$2;} END {if(enabled == "Yes") print "http://" server ":" port}'\''`'

	export ARCHFLAGS="-arch x86_64"
	export COPYFILE_DISABLE=true #for stopping those damned ._ files
	export PATH=/opt/homebrew/bin:/opt/homebrew/sbin:/usr/local/bin:/usr/local/sbin:/usr/bin:/bin:/usr/sbin:/sbin:/usr/X11/bin:`xcode-select -print-path`/usr/bin:$HOME/Applications:$HOME/.fzf/fzf/bin:/Library/TeX/texbin:
	export TEXINPUTS=".:.//:/usr/local/texlive/2023basic/texmf-dist/tex/latex//:/usr/local/texlive/2023basic/texmf-dist/tex/generic//:$HOME/working/reposs/tex//:"
	export GNUTERM=x11 # for Octave

	#bash completion
	BREW_PREFIX=`brew --prefix`
	if [ -f $BREW_PREFIX/etc/bash_completion ]; then
		 . $BREW_PREFIX/etc/bash_completion
		 . $BREW_PREFIX/completions/bash/brew
		# . $BREW_PREFIX/etc/bash_completion.d/git-completion.bash
	fi
else
	alias ls='ls --color=auto'
	alias grep='grep --color=auto'

	# local path modifications
	export PATH=$HOME/bin:$HOME/local/bin:$GOPATH/bin:$PATH:$HOME/repos/depot_tools:$HOME/goma:$HOME/.fzf/fzf/bin
	# export TERM=xterm-256color
	export CHROME_DEVEL_SANDBOX=/usr/local/sbin/chrome-devel-sandbox

	ssource "/etc/bash_completion"
	ssource $HOME/repos/ninja/misc/bash-completion
fi
