#! bash

# common
export no_proxy=".schwa.org"

alias rm='rm -i'
alias ll='ls -hlF'
alias la='ls -ha'
alias  l='ls -halF'
alias less='less -R'
alias tmux-create='~/dotfiles/tmux-create'
alias tm='tmux'
export PYTHONSTARTUP=$HOME/.pythonrc.py

if [ `uname` = 'Darwin' ]; then
	alias top='top -s1 -F -R -o cpu'
	# alias tmux='tmux -f ~/.tmux-osx.conf'
	alias vim='reattach-to-user-namespace vim'
	alias ls='ls -G'
	alias grep='grep --color=auto'
	alias volcheck='sudo fsck_hfs -f -c 2200m' # /dev/disk2
	alias postgres-start='pg_ctl -D /usr/local/var/postgres -l /usr/local/var/postgres/server.log start'
	alias postgres-stop='pg_ctl -D /usr/local/var/postgres stop -s -m fast'
	alias fixopenwith='/System/Library/Frameworks/CoreServices.framework/Frameworks/LaunchServices.framework/Support/lsregister -kill -r -domain local -domain system -domain user'
	alias proxy='export http_proxy=`networksetup -getwebproxy Wi-Fi | awk '\''{ if(NR == 1) enabled=$2; else if(NR == 2) server=$2; else if(NR == 3) port=$2;} END {if(enabled == "Yes") print "http://" server ":" port}'\''`'

	#bash completion
	BREW_PREFIX=`brew --prefix`
	if [ -f $BREW_PREFIX/etc/bash_completion ]; then
		. $BREW_PREFIX/etc/bash_completion
		. $BREW_PREFIX/Library/Contributions/brew_bash_completion.sh
		. $BREW_PREFIX/etc/bash_completion.d/git-completion.bash
	fi

	export ARCHFLAGS="-arch x86_64"
	export COPYFILE_DISABLE=true #for stopping those damned ._ files
	export PATH=/usr/local/bin:/usr/local/sbin:/usr/bin:/bin:/usr/sbin:/sbin:/usr/X11/bin:/usr/texbin:`xcode-select -print-path`/usr/bin:/usr/local/texlive/2014basic/bin/universal-darwin:$HOME/Applications
	export TEXINPUTS=".:.//:/usr/local/texlive/2014basic/texmf-dist/tex/latex//:/usr/local/texlive/2014basic/texmf-dist/tex/generic//:$HOME/working/reposs/tex//:"
	export GNUTERM=x11 # for Octave
else
	alias ls='ls --color=auto'
	alias grep='grep --color=auto'

	# local path modifications
	export PATH=$HOME/bin:$HOME/local/bin:$PATH
	export TEXINPUTS=".:${HOME}/repos/tex//:"
	export CANDC_MODELS="${HOME}/candc/models"

	ssource "/etc/bash_completion"
fi
