#! bash

# common
export no_proxy=".schwa.org"

alias rm='rm -i'
alias ll='ls -hlF'
alias la='ls -ha'
alias  l='ls -halF'
alias less='less -R'
alias tmux-create='~/dotfiles/tmux-create'
alias tm='tmux'
export PYTHONSTARTUP=$HOME/.pythonrc.py

if [ `uname` = 'Darwin' ]; then
	alias top='top -s1 -F -R -o cpu'
	alias tmux='tmux -f ~/.tmux-osx.conf'
	alias vim='reattach-to-user-namespace vim'
	alias ls='ls -G'
	alias grep='grep --color=auto'
	alias volcheck='sudo fsck_hfs -f -c 2200m' # /dev/disk2
	alias postgres-start='pg_ctl -D /usr/local/var/postgres -l /usr/local/var/postgres/server.log start'
	alias postgres-stop='pg_ctl -D /usr/local/var/postgres stop -s -m fast'
	alias fixopenwith='/System/Library/Frameworks/CoreServices.framework/Frameworks/LaunchServices.framework/Support/lsregister -kill -r -domain local -domain system -domain user'
	alias proxy='export http_proxy=`networksetup -getwebproxy Wi-Fi | awk '\''{ if(NR == 1) enabled=$2; else if(NR == 2) server=$2; else if(NR == 3) port=$2;} END {if(enabled == "Yes") print "http://" server ":" port}'\''`'

	#bash completion
	BREW_PREFIX=`brew --prefix`
	if [ -f $BREW_PREFIX/etc/bash_completion ]; then
		. $BREW_PREFIX/etc/bash_completion
		. $BREW_PREFIX/Library/Contributions/brew_bash_completion.sh
		. $BREW_PREFIX/etc/bash_completion.d/git-completion.bash
	fi

	export ARCHFLAGS="-arch x86_64"
	export COPYFILE_DISABLE=true #for stopping those damned ._ files
	export PATH=/usr/local/bin:/usr/local/sbin:/usr/bin:/bin:/usr/sbin:/sbin:/usr/X11/bin:/usr/texbin::`xcode-select -print-path`/usr/bin:/usr/local/texlive/2014basic/bin/universal-darwin
	export TEXINPUTS=".:.//:$HOME/working/reposs/tex//:"
	export GNUTERM=x11 # for Octave
else
	alias ls='ls --color=auto'
	alias grep='grep --color=auto'

	# local path modifications
	export PATH=$HOME/bin:$HOME/local/bin:$PATH:/n/schwafs/home/schwa/bin:/n/schwafs/home/dom/local/scala-2.10.0/bin
	export TEXINPUTS=".:${HOME}/repos/tex//:"
	export CANDC_MODELS="${HOME}/candc/models"
	export CLASSPATH=$CLASSPATH:${HOME}/utils/weka/weka.jar:/mnt/home/dom/utils/libsvm/java/libsvm.jar
	export PYTHONPATH="${HOME}/local/eggs/lib/python2.6/site-packages:${HOME}/local/eggs/lib/python2.7/site-packages:${HOME}/repos/ncss/ncssbook:${HOME}/repos/wikipedia:${HOME}/repos/schwapy:$PYTHONPATH"
	export SCHWA_WORKSPACE=$HOME/repos
	export JAVA_HOME=/usr/lib/jvm/java-8-oracle
	export SCALA_HOME=/n/schwafs/home/dom/local/scala-2.10.0

	# Add the schwa repo.
	SCHWA_BUILD=$SCHWA_WORKSPACE/schwa/build/lib.linux-x86_64-2.7
	SCHWA_LIB=$SCHWA_WORKSPACE/schwa/lib
	SCHWA_BIN=$SCHWA_WORKSPACE/schwa/bin
	pathprepend /n/schwafs/home/schwa/64/lib LD_LIBRARY_PATH
	if [ -d "$SCHWA_BUILD" ]; then
			echo "Adding $SCHWA_BUILD to PYTHONPATH" >&2
			pathprepend $SCHWA_BUILD PYTHONPATH
	else
			echo "Not adding $SCHWA_BUILD to PYTHONPATH (missing directory)" >&2
	fi
	if [ -d "$SCHWA_LIB" ]; then
			echo "Adding $SCHWA_LIB to LD_LIBRARY_PATH" >&2
			pathprepend $SCHWA_LIB LD_LIBRARY_PATH
	else
			echo "Not adding $SCHWA_LIB to LD_LIBRARY_PATH (missing directory)" >&2
	fi
	if [ -d "$SCHWA_BIN" ]; then
			echo "Adding $SCHWA_BIN to PATH" >&2
			pathprepend $SCHWA_BIN PATH
	else
			echo "Not adding $SCHWA_BIN to LD_LIBRARY_PATH (missing directory)" >&2
	fi
	pathprepend /n/schwafs/home/dom/local/lib LD_LIBRARY_PATH

	ssource "/etc/bash_completion"
fi
